"""Regenerate DECISIONS.md from @decision annotations in the source tree.

Scans ``src/adversary_pursuit/**/*.py`` for ``@decision DEC-*`` annotation
blocks and emits a grouped-by-component ``DECISIONS.md`` index at the
project root.

Usage::

    # Write DECISIONS.md to project root (default):
    python3 scripts/regen_decisions.py

    # Dry-run: print to stdout instead of writing to disk:
    python3 scripts/regen_decisions.py --dry-run

Annotation format (two supported forms):

1. Docstring annotations (no leading ``#``):

   .. code-block:: python

       @decision DEC-BADGE-001
       @title workspace_stats dict contract for badge evaluation
       @status accepted
       @rationale Badge.check_award receives a plain stats dict ...

2. Inline comment annotations (with leading ``# ``):

   .. code-block:: python

       # @decision DEC-CONFIG-006
       # @title auto_pivot_depth retained for TOML backward compatibility
       # @status accepted
       # @rationale The pre-F60 recursion limit is superseded ...

The component name is derived from the top-level sub-package folder directly
inside ``src/adversary_pursuit/`` (e.g. ``gamification``, ``core``, ``dossier``).
The DEC-ID prefix (first token after ``DEC-``) is used as the component label
when no folder component can be inferred (rare; falls back to the full prefix).

@decision DEC-HYGIENE-REGEN-001
@title scripts/regen_decisions.py — single-authority DECISIONS.md generator
@status accepted
@rationale DECISIONS.md was previously "auto-generated by stop.sh" but stop.sh
           was never created; the file went 42 days stale. This script is the
           sole authority for DECISIONS.md content. It reads @decision annotations
           directly from source (no stop-hook wiring in this slice — manual
           invocation only). Idempotent: same source → same content modulo
           timestamp. Loud failure on malformed annotations: prints to stderr
           and continues rather than silently dropping entries.
"""

from __future__ import annotations

import argparse
import datetime
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterator

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Root of the source package to scan, relative to project root.
_SOURCE_ROOT = "src/adversary_pursuit"

# Output file, relative to project root.
_OUTPUT_FILE = "DECISIONS.md"

# DEC-ID pattern: DEC followed by one or more dash-separated UPPERCASE/digit/
# underscore segments.  e.g. DEC-BADGE-001, DEC-M4-PERSIST-002.
_DEC_ID_RE = re.compile(r"^DEC-[A-Z0-9_][A-Z0-9_-]*$")

# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------


@dataclass
class DecisionEntry:
    """A single parsed @decision annotation."""

    dec_id: str
    title: str
    status: str
    rationale: str
    source_path: str  # repo-relative path
    component: str  # top-level folder label (e.g. "gamification")


# ---------------------------------------------------------------------------
# Parsing
# ---------------------------------------------------------------------------


def _strip_comment_prefix(line: str) -> str:
    """Remove a leading ``# `` (or ``#\t``) from an annotation line.

    Used to normalise inline-comment annotations so the two annotation
    styles share the same field-extraction logic.
    """
    stripped = line.lstrip()
    if stripped.startswith("# "):
        return stripped[2:]
    if stripped.startswith("#\t"):
        return stripped[2:]
    if stripped.startswith("#"):
        return stripped[1:]
    return stripped


def _iter_annotation_blocks(
    lines: list[str],
    source_label: str,
) -> Iterator[tuple[int, list[str]]]:
    """Yield (start_line_number, raw_block_lines) for each @decision block.

    Handles both docstring-style (bare ``@decision ...``) and inline-comment
    style (``# @decision ...``).  A block ends at the next blank-after-fields
    boundary, the next ``@decision``, or EOF.

    ``start_line_number`` is 1-based.
    """
    in_block = False
    block_start = 0
    block_lines: list[str] = []

    def _is_decision_line(raw: str) -> bool:
        stripped = _strip_comment_prefix(raw).strip()
        return stripped.startswith("@decision ")

    for lineno, raw in enumerate(lines, start=1):
        if _is_decision_line(raw):
            if in_block and block_lines:
                yield block_start, block_lines
            in_block = True
            block_start = lineno
            block_lines = [_strip_comment_prefix(raw).strip()]
        elif in_block:
            norm = _strip_comment_prefix(raw).strip()
            if not norm:
                # Blank line ends the block.
                yield block_start, block_lines
                in_block = False
                block_lines = []
            else:
                block_lines.append(norm)

    if in_block and block_lines:
        yield block_start, block_lines


def _parse_block(
    block_lines: list[str],
    source_label: str,
    lineno: int,
) -> DecisionEntry | None:
    """Parse a raw annotation block into a DecisionEntry.

    Returns None and emits a stderr warning when the block is malformed.
    """
    # First line must be ``@decision DEC-...``
    first = block_lines[0]
    if not first.startswith("@decision "):
        print(
            f"WARN: malformed annotation at {source_label}:{lineno} — "
            f"block does not start with '@decision': {first!r}",
            file=sys.stderr,
        )
        return None

    parts = first.split(None, 2)
    if len(parts) < 2:
        print(
            f"WARN: malformed annotation at {source_label}:{lineno} — "
            f"no DEC-ID after '@decision': {first!r}",
            file=sys.stderr,
        )
        return None

    dec_id = parts[1].rstrip(":")
    if not _DEC_ID_RE.match(dec_id):
        print(
            f"WARN: suspicious DEC-ID at {source_label}:{lineno} — "
            f"'{dec_id}' does not match DEC-ID pattern; keeping anyway.",
            file=sys.stderr,
        )

    title = ""
    status = ""
    rationale_lines: list[str] = []
    in_rationale = False

    for line in block_lines[1:]:
        if line.startswith("@title "):
            title = line[len("@title ") :].strip()
            in_rationale = False
        elif line.startswith("@status "):
            status = line[len("@status ") :].strip()
            in_rationale = False
        elif line.startswith("@rationale ") or line.startswith("@rationale"):
            tail = line[len("@rationale") :].lstrip()
            if tail:
                rationale_lines.append(tail)
            in_rationale = True
        elif line.startswith("@"):
            # Another tag — stop collecting rationale
            in_rationale = False
        elif in_rationale:
            rationale_lines.append(line)

    if not title:
        print(
            f"WARN: annotation {dec_id} at {source_label}:{lineno} has no @title; "
            "using DEC-ID as title.",
            file=sys.stderr,
        )
        title = dec_id

    if not status:
        status = "accepted"

    # Collapse multi-line rationale to a single sentence (first non-empty line).
    rationale = ""
    for rline in rationale_lines:
        rline = rline.strip()
        if rline:
            rationale = rline
            break

    return DecisionEntry(
        dec_id=dec_id,
        title=title,
        status=status,
        rationale=rationale,
        source_path=source_label,
        component="",  # filled in by caller
    )


# ---------------------------------------------------------------------------
# Component labelling
# ---------------------------------------------------------------------------


def _component_from_path(repo_relative_path: str) -> str:
    """Derive a component label from the file's position in the source tree.

    The label is the top-level sub-package name directly inside
    ``src/adversary_pursuit/`` (e.g. ``gamification``, ``core``, ``dossier``).
    Files at the package root (e.g. ``__init__.py``) use ``core`` as a fallback.

    The label is uppercased for the DECISIONS.md section heading.
    """
    # Normalise to forward slashes
    posix = repo_relative_path.replace("\\", "/")
    # Expected: src/adversary_pursuit/<component>/...
    prefix = "src/adversary_pursuit/"
    if posix.startswith(prefix):
        remainder = posix[len(prefix) :]
        parts = remainder.split("/")
        if len(parts) >= 2:
            return parts[0].upper()
        # File at package root level
        return "CORE"
    return "UNKNOWN"


# ---------------------------------------------------------------------------
# Scanning
# ---------------------------------------------------------------------------


def scan_source_tree(project_root: Path) -> list[DecisionEntry]:
    """Scan the source tree and return all parsed DecisionEntry objects.

    Entries are returned in file-scan order (alphabetical by path within
    each component).  Deduplication of DEC-IDs uses last-seen wins within
    the same file; cross-file duplicates are reported as warnings but both
    are kept (plan annotations can reference the same DEC-ID from multiple
    call sites).
    """
    source_root = project_root / _SOURCE_ROOT
    assert source_root.exists(), (
        f"Source root not found: {source_root}\n"
        "Run this script from the project root or check _SOURCE_ROOT."
    )

    entries: list[DecisionEntry] = []
    seen_ids: dict[str, str] = {}  # dec_id → first source file (for dup warnings)

    py_files = sorted(source_root.rglob("*.py"))
    assert py_files, f"No Python files found under {source_root}"

    for py_file in py_files:
        # Skip __pycache__
        if "__pycache__" in py_file.parts:
            continue

        repo_rel = str(py_file.relative_to(project_root))
        component = _component_from_path(repo_rel)

        try:
            text = py_file.read_text(encoding="utf-8", errors="replace")
        except OSError as exc:
            print(
                f"WARN: cannot read {repo_rel}: {exc}",
                file=sys.stderr,
            )
            continue

        lines = text.splitlines()
        for lineno, block_lines in _iter_annotation_blocks(lines, repo_rel):
            entry = _parse_block(block_lines, repo_rel, lineno)
            if entry is None:
                continue
            entry.source_path = repo_rel
            entry.component = component

            if entry.dec_id in seen_ids and seen_ids[entry.dec_id] != repo_rel:
                print(
                    f"INFO: DEC-ID {entry.dec_id} appears in multiple files: "
                    f"{seen_ids[entry.dec_id]} and {repo_rel}",
                    file=sys.stderr,
                )
            seen_ids[entry.dec_id] = repo_rel
            entries.append(entry)

    return entries


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------


def render_decisions_md(entries: list[DecisionEntry], timestamp: str) -> str:
    """Render the DECISIONS.md content from a list of DecisionEntry objects."""
    lines: list[str] = [
        "# Decision Registry",
        "> Auto-generated by scripts/regen_decisions.py from @decision annotations in source code.",
        f"> Last updated: {timestamp}",
        "",
        "## By Component",
    ]

    # Group by component, preserving alphabetical component order
    components: dict[str, list[DecisionEntry]] = {}
    for entry in entries:
        components.setdefault(entry.component, []).append(entry)

    for comp in sorted(components):
        lines.append(f"### {comp}")
        for e in components[comp]:
            lines.append(f"- **{e.dec_id}**: {e.title}")
            lines.append(f"  - Source: `{e.source_path}`")
            lines.append(f"  - Status: {e.status}")
            if e.rationale:
                lines.append(f"  - Rationale: {e.rationale}")
            lines.append("")  # blank line between entries

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Regenerate DECISIONS.md from @decision annotations in src/adversary_pursuit/**/*.py"
        )
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print generated content to stdout instead of writing DECISIONS.md",
    )
    args = parser.parse_args()

    # Resolve project root: script lives at <project_root>/scripts/regen_decisions.py
    script_dir = Path(__file__).resolve().parent
    project_root = script_dir.parent

    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")

    print(f"Scanning {project_root / _SOURCE_ROOT} ...", file=sys.stderr)
    entries = scan_source_tree(project_root)
    print(f"Found {len(entries)} @decision annotations.", file=sys.stderr)

    content = render_decisions_md(entries, timestamp)

    if args.dry_run:
        print(content)
    else:
        output_path = project_root / _OUTPUT_FILE
        output_path.write_text(content, encoding="utf-8")
        print(f"Written: {output_path}", file=sys.stderr)
        print(
            f"  {len(entries)} decisions across {len({e.component for e in entries})} components.",
            file=sys.stderr,
        )


if __name__ == "__main__":
    main()
